### ISSUE TITLE
Possible to change increment amount?

### ISSUE THREAD

**Issue by BWPanda** [Deminder/osd-volume-number#1]
I love this extension, thanks so much for it!

When I change volume, it increments/decrements in steps of 6 (e.g. volume is 50, pressing Volume Up change it to 56, then 62, etc.). Is there any way this extension could allow changing this step amount?

If not, any suggestions on how else to do so?

**Comment by Deminder** [comment]
I'm glad you like it!
 
- `+-volume-step (default 6)` by:  `Volume Up/Down`
- `+-4` by: `Scroll Up/Down` (while hovering on volume Indicator)
- `+-2` by: `Shift` + `Volume Up/Down`

I think, the `+-2` step is precise enough, however, you could set `volume-step` to `1` with:
```shell
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-step 1
```
The step `VOLUME_STEP_PRECISE=2` with the Shift key is constant. The media-keys `VOLUME_DOWN_KEY`/`VOLUME_UP_KEY` are handled here: https://github.com/GNOME/gnome-settings-daemon/blob/0ad4e34c54d848481adeabb46ff8c78789daf1b9/plugins/media-keys/gsd-media-keys-manager.c#L1565-L1579

**Comment by BWPanda** [comment]
> ...however, you could set volume-step to 1 with:
>
> `dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-step 1`

I just discovered this myself too! Since it's possible to change in Gnome itself, no need for it here then :-)
